<?php

namespace ContainerZaHtjrz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F7beiKBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f7beiKB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f7beiKB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commande' => ['privates', '.errored..service_locator.f7beiKB.App\\Entity\\Commande', NULL, 'Cannot autowire service ".service_locator.f7beiKB": it references class "App\\Entity\\Commande" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'commande' => 'App\\Entity\\Commande',
            'doctrine' => '?',
        ]);
    }
}
