<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKBEwrAa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKBEwrAa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKBEwrAa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKBEwrAa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKBEwrAa\App_KernelDevDebugContainer([
    'container.build_hash' => 'KBEwrAa',
    'container.build_id' => '9a10a6b0',
    'container.build_time' => 1669200548,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKBEwrAa');
